/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Direction = { 'buy' : null } |
  { 'sell' : null };
export interface HoldingView {
  'avgPrice' : bigint,
  'quantity' : bigint,
  'symbol' : Symbol,
}
export interface PortfolioSummary {
  'returnPct' : bigint,
  'balance' : bigint,
  'totalInvested' : bigint,
  'totalPnl' : bigint,
}
export type Symbol = string;
export type Timestamp = bigint;
export type TradeResult = { 'ok' : TradeView } |
  { 'err' : string };
export interface TradeView {
  'id' : bigint,
  'direction' : Direction,
  'timestamp' : Timestamp,
  'quantity' : bigint,
  'price' : bigint,
  'symbol' : Symbol,
}
export interface _SERVICE {
  'addToWatchlist' : ActorMethod<[Symbol], undefined>,
  'buy' : ActorMethod<[Symbol, bigint, bigint], TradeResult>,
  'getHoldings' : ActorMethod<[], Array<HoldingView>>,
  'getPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getTradeHistory' : ActorMethod<[], Array<TradeView>>,
  'getWatchlist' : ActorMethod<[], Array<Symbol>>,
  'register' : ActorMethod<[], undefined>,
  'removeFromWatchlist' : ActorMethod<[Symbol], undefined>,
  'sell' : ActorMethod<[Symbol, bigint, bigint], TradeResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];