/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Symbol = IDL.Text;
export const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Timestamp = IDL.Int;
export const TradeView = IDL.Record({
  'id' : IDL.Nat,
  'direction' : Direction,
  'timestamp' : Timestamp,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'symbol' : Symbol,
});
export const TradeResult = IDL.Variant({ 'ok' : TradeView, 'err' : IDL.Text });
export const HoldingView = IDL.Record({
  'avgPrice' : IDL.Nat,
  'quantity' : IDL.Nat,
  'symbol' : Symbol,
});
export const PortfolioSummary = IDL.Record({
  'returnPct' : IDL.Int,
  'balance' : IDL.Nat,
  'totalInvested' : IDL.Nat,
  'totalPnl' : IDL.Int,
});

export const idlService = IDL.Service({
  'addToWatchlist' : IDL.Func([Symbol], [], []),
  'buy' : IDL.Func([Symbol, IDL.Nat, IDL.Nat], [TradeResult], []),
  'getHoldings' : IDL.Func([], [IDL.Vec(HoldingView)], ['query']),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
  'getTradeHistory' : IDL.Func([], [IDL.Vec(TradeView)], ['query']),
  'getWatchlist' : IDL.Func([], [IDL.Vec(Symbol)], ['query']),
  'register' : IDL.Func([], [], []),
  'removeFromWatchlist' : IDL.Func([Symbol], [], []),
  'sell' : IDL.Func([Symbol, IDL.Nat, IDL.Nat], [TradeResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Symbol = IDL.Text;
  const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Timestamp = IDL.Int;
  const TradeView = IDL.Record({
    'id' : IDL.Nat,
    'direction' : Direction,
    'timestamp' : Timestamp,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'symbol' : Symbol,
  });
  const TradeResult = IDL.Variant({ 'ok' : TradeView, 'err' : IDL.Text });
  const HoldingView = IDL.Record({
    'avgPrice' : IDL.Nat,
    'quantity' : IDL.Nat,
    'symbol' : Symbol,
  });
  const PortfolioSummary = IDL.Record({
    'returnPct' : IDL.Int,
    'balance' : IDL.Nat,
    'totalInvested' : IDL.Nat,
    'totalPnl' : IDL.Int,
  });
  
  return IDL.Service({
    'addToWatchlist' : IDL.Func([Symbol], [], []),
    'buy' : IDL.Func([Symbol, IDL.Nat, IDL.Nat], [TradeResult], []),
    'getHoldings' : IDL.Func([], [IDL.Vec(HoldingView)], ['query']),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
    'getTradeHistory' : IDL.Func([], [IDL.Vec(TradeView)], ['query']),
    'getWatchlist' : IDL.Func([], [IDL.Vec(Symbol)], ['query']),
    'register' : IDL.Func([], [], []),
    'removeFromWatchlist' : IDL.Func([Symbol], [], []),
    'sell' : IDL.Func([Symbol, IDL.Nat, IDL.Nat], [TradeResult], []),
  });
};

export const init = ({ IDL }) => { return []; };