/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Symbol = string;
export interface HoldingView {
    avgPrice: bigint;
    quantity: bigint;
    symbol: Symbol;
}
export interface PortfolioSummary {
    returnPct: bigint;
    balance: bigint;
    totalInvested: bigint;
    totalPnl: bigint;
}
export type TradeResult = {
    __kind__: "ok";
    ok: TradeView;
} | {
    __kind__: "err";
    err: string;
};
export interface TradeView {
    id: bigint;
    direction: Direction;
    timestamp: Timestamp;
    quantity: bigint;
    price: bigint;
    symbol: Symbol;
}
export enum Direction {
    buy = "buy",
    sell = "sell"
}
export interface backendInterface {
    addToWatchlist(symbol: Symbol): Promise<void>;
    buy(symbol: Symbol, quantity: bigint, pricePaise: bigint): Promise<TradeResult>;
    getHoldings(): Promise<Array<HoldingView>>;
    getPortfolioSummary(): Promise<PortfolioSummary>;
    getTradeHistory(): Promise<Array<TradeView>>;
    getWatchlist(): Promise<Array<Symbol>>;
    register(): Promise<void>;
    removeFromWatchlist(symbol: Symbol): Promise<void>;
    sell(symbol: Symbol, quantity: bigint, pricePaise: bigint): Promise<TradeResult>;
}
import type { Direction as _Direction, Symbol as _Symbol, Timestamp as _Timestamp, TradeResult as _TradeResult, TradeView as _TradeView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToWatchlist(arg0: Symbol): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0);
            return result;
        }
    }
    async buy(arg0: Symbol, arg1: bigint, arg2: bigint): Promise<TradeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.buy(arg0, arg1, arg2);
                return from_candid_TradeResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buy(arg0, arg1, arg2);
            return from_candid_TradeResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHoldings(): Promise<Array<HoldingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHoldings();
            return result;
        }
    }
    async getPortfolioSummary(): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary();
            return result;
        }
    }
    async getTradeHistory(): Promise<Array<TradeView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeHistory();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeHistory();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWatchlist(): Promise<Array<Symbol>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return result;
        }
    }
    async register(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register();
            return result;
        }
    }
    async removeFromWatchlist(arg0: Symbol): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async sell(arg0: Symbol, arg1: bigint, arg2: bigint): Promise<TradeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sell(arg0, arg1, arg2);
                return from_candid_TradeResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sell(arg0, arg1, arg2);
            return from_candid_TradeResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Direction_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TradeResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeResult): TradeResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_TradeView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeView): TradeView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    direction: _Direction;
    timestamp: _Timestamp;
    quantity: bigint;
    price: bigint;
    symbol: _Symbol;
}): {
    id: bigint;
    direction: Direction;
    timestamp: Timestamp;
    quantity: bigint;
    price: bigint;
    symbol: Symbol;
} {
    return {
        id: value.id,
        direction: from_candid_Direction_n5(_uploadFile, _downloadFile, value.direction),
        timestamp: value.timestamp,
        quantity: value.quantity,
        price: value.price,
        symbol: value.symbol
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TradeView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TradeView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TradeView_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Direction {
    return "buy" in value ? Direction.buy : "sell" in value ? Direction.sell : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeView>): Array<TradeView> {
    return value.map((x)=>from_candid_TradeView_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
